{% set version = "1.0.6" %}

package:
  name: salvus_mesher_lite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/salvus_mesher_lite/salvus_mesher_lite-{{ version }}.tar.gz
  sha256: 7845275d1bd627f6358c586c44feb479e973ea3e6aea808ed65f373c827e3ac8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - numpy
    - scipy
    - matplotlib
    - jsonschema
    - pyyaml
    - pyexodus

test:
  imports:
    - salvus_mesher_lite
    - salvus_mesher_lite.tests
  requires:
    - pytest
    - flake8
    - pytest-mpl
    - mock  # [py27]

about:
  home: https://salvus.io
  # https://gitlab.com/Salvus/SalvusMesherLite/issues/1
  license: GPL-3.0
  summary: 'Salvus mesher for AxiSEM meshes'

extra:
  recipe-maintainers:
    - krischer
    - martinvandriel
