travis:
  secure:
    BINSTAR_TOKEN: DDeBleSC1dJyNtXbyUZgRPXJVdBc6NVvdmyVv9R95RpYhanUaggQZxuwAAw9DJgiXT+TmeD69200lLhh/PnnQiHtEYCl48Ef8/4IjND91SAP+9Kx43uAudfIgeosbM/AAK04t2iZtJ86bqI4uUb+CIMYFtZUusu1f2P1qt32eOigrgKMRvlirfBmEBdpynNEyPVcC/ApKHCCzsBvO0Wtus4n3TV3z9c8SD8MUP+ThJERWdeMO7pa0MV126UvIDffbrHk5IyCBID3EIGGSbQ12xoXaoRxRptX5rRcleXQRyKjxHF1APPqiNH3FVpzjokGJRhTXSfjkKPyULRhFCouhG822KdHjrUz3XTWCKxB0fDIdTaGD0atfOyEMzSIap47+/CXg33KWwP21kIio+fXWaH0MUXPKbVwXjJ707hb5PT4CYcnqXihHCMaq0J1DZR3Q37PDBnpYBoR1jF35NPlcMAoohlvBZalxmj0BgrkRTQh5otv6/FH9Zg1oQ3Ixc6JFfKExdFvW74FZOH5XaSL8bWEFfoLgZbf0e2v50+AD4/yjStQmzTkL3zDsffavDt5uRSVcF5nugBCxg46uEU2cV0e+P0QudC+iWZ1htxl2e39UuXDjGXcoV9Kb7FaHKrgZOtiwo7Cef3VR3TbgPwD9Hm1cqyTVwbu6bleqjkxIQU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
