travis:
  secure:
    BINSTAR_TOKEN: mirOAIg/pDOw2hL5heBGtliRa95eVLhCMKLv5ljOiAofEcoNnEDUX/htiGD+5n+glNMe+rWUF+O2ynjt9T0vXRBaJ7fVbYvIEapLCLlbOPZFVOILhjTXZa/WGb0GcDHBo+ai7i8Qea9t1YdCAfrma6tK54d7cMuo6BAUmoGDTZUpQKqzXYLuKjgVzab6n1UN0VuoYqbzCUP6IucB5ZGrav00CHbQhiYM6qoZnfDfo7pNK9hXRJjyivWjcBTVR4jxY9ijFrnZcLnNWMEGrFzQcHATeweFYC4/9sSHrzc5SDXRfxvmXB/aAiG6N1r4/zI36ivr0W0oV1tgMXuG0cdHk59Dkcs2e67rHPvqZNxn6IPFsr/HUv/zEoeXi+AM7QtjVvJPj8hy3YkAht9UabBofU7j+b9sovVwWVmd9un1gkkdPPBx0hOcX0q8CPAwJfqVb0qvAr4VYeo5ljuQqp9MjNNxt1KbGkbjSgpNV1sMlIN7oAdNRx2HeQHF+/yem3lRb4Q6JlZphn6k3cwTD16fbqZL5h/VPvjQrkn7ntM3kkvi9DWXmuuNWU1/hKjcINJHF5C2RzV8vueQqETMitmZJibVXzpLYsa0IUaVmiI98kqRaRpu51DelY/sOQDVRU5eKeoqEpTffkzCXip39Sdu+OEC+oC7X69Ey1/jFErW9gg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
